CREATE TABLE IF NOT EXISTS usuarios (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  foto_url TEXT,
  creado_en TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS lugares (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(100) UNIQUE NOT NULL,
  descripcion TEXT NOT NULL,
  imagen TEXT NOT NULL,
  rating FLOAT NOT NULL,
  precio VARCHAR(10) NOT NULL,
  latitud DOUBLE PRECISION NOT NULL,
  longitud DOUBLE PRECISION NOT NULL,
  direccion TEXT NOT NULL,
  como_llegar TEXT,
  creado_en TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS resenas (
  id SERIAL PRIMARY KEY,
  lugar_id INTEGER REFERENCES lugares(id) ON DELETE CASCADE,
  usuario_id INTEGER REFERENCES usuarios(id) ON DELETE CASCADE,
  comentario TEXT NOT NULL,
  rating INTEGER DEFAULT 5,
  fecha TIMESTAMP DEFAULT NOW(),
  UNIQUE(usuario_id, lugar_id)
);

CREATE TABLE IF NOT EXISTS favoritos (
  id SERIAL PRIMARY KEY,
  usuario_id INTEGER REFERENCES usuarios(id) ON DELETE CASCADE,
  lugar_id INTEGER REFERENCES lugares(id) ON DELETE CASCADE,
  creado_en TIMESTAMP DEFAULT NOW(),
  UNIQUE(usuario_id, lugar_id)
);
